"""On-demand cached single-function Ghidra decompilation."""

from __future__ import annotations

import json
import os
import subprocess
from pathlib import Path
from typing import Any

from genie.common import ROOT, load_yaml, parse_int, write_json

from .database import AnalysisDatabase


def _config() -> dict[str, Any]:
    return dict(load_yaml(ROOT / "re/config/ghidra.yml") or {})


def _cache_paths(database: AnalysisDatabase, address: int, cache_dir: Path | None) -> tuple[Path, Path, Path]:
    directory = Path(cache_dir) if cache_dir is not None else database.root / "decompile"
    stem = f"{address:08X}"
    return directory / f"{stem}.txt", directory / f"{stem}.json", directory / f"{stem}.request.json"


def _project(config: dict[str, Any], project_dir: Path | None) -> tuple[Path, str]:
    values = config.get("ghidra", {})
    directory = (project_dir or ROOT / values["project_dir"]).resolve()
    name = str(values["project_name"])
    if not (directory / f"{name}.gpr").exists() and not (directory / f"{name}.rep").exists():
        raise FileNotFoundError(f"Ghidra project not found: {directory}; run `genie ghidra scan`")
    return directory, name


def decompile_function(
    address: int,
    *,
    database: AnalysisDatabase,
    cache_dir: Path | None = None,
    project_dir: Path | None = None,
    force: bool = False,
) -> dict[str, Any]:
    """Decompile the containing function and cache its pseudocode."""

    address = parse_int(address)
    function = database.function(address)
    if function is None:
        raise ValueError(f"no function contains 0x{address:08X}")
    entry = parse_int(function["address"])
    text_path, report_path, request_path = _cache_paths(database, entry, cache_dir)
    if text_path.is_file() and not force:
        return {
            "status": "cached",
            "address": f"0x{entry:08X}",
            "name": function.get("name"),
            "path": str(text_path),
            "report": str(report_path) if report_path.is_file() else None,
        }

    config = _config()
    project, project_name = _project(config, project_dir)
    install = ROOT / config["ghidra"]["install_dir"]
    headless = install / "support" / ("pyghidraRun.bat" if os.name == "nt" else "pyghidraRun")
    if not headless.is_file():
        raise FileNotFoundError(f"Ghidra launcher not found: {headless}; run `genie ghidra setup`")

    text_path.parent.mkdir(parents=True, exist_ok=True)
    request = {
        "format": "openaladdin-targeted-decompile-request-v1",
        "rom": database.metadata.get("rom"),
        "focus": {"address": f"0x{entry:08X}", "source": "genie ghidra decompile"},
        "targets": [{"address": f"0x{entry:08X}", "name": function.get("name")}],
    }
    write_json(request_path, request)
    command = [
        str(headless),
        "-H",
        str(project),
        project_name,
        "-process",
        "-readOnly",
        "-scriptPath",
        str(ROOT / "re/ghidra/scripts"),
        "-postScript",
        "ExportTargetedDecompile.py",
        str(request_path),
        str(report_path),
    ]
    environment = os.environ.copy()
    environment["GHIDRA_INSTALL_DIR"] = str(install)
    environment["OPENALADDIN_ROOT"] = str(ROOT)
    venv_bin = ROOT / ".tools/venv/bin"
    if venv_bin.is_dir():
        environment["PATH"] = str(venv_bin) + os.pathsep + environment.get("PATH", "")
    try:
        subprocess.run(command, cwd=ROOT, env=environment, check=True)
    except subprocess.CalledProcessError as error:
        raise RuntimeError(f"Ghidra decompile failed with status {error.returncode}") from error

    report = json.loads(report_path.read_text(encoding="utf-8"))
    rows = [row for row in report.get("targets", []) if row.get("address") == f"0x{entry:06X}"]
    if not rows:
        rows = [row for row in report.get("targets", []) if parse_int(row.get("address", -1)) == entry]
    if not rows:
        raise RuntimeError(f"Ghidra decompile report did not contain 0x{entry:08X}")
    row = rows[0]
    status = str(row.get("status", "decompile_failed"))
    pseudocode = row.get("c")
    if status != "decompiled" or not isinstance(pseudocode, str):
        raise RuntimeError(row.get("error") or f"Ghidra could not decompile 0x{entry:08X}")
    text_path.write_text(
        "\n".join([
            "/* Generated by `genie ghidra decompile`; edit tracked knowledge instead. */",
            f"/* address: 0x{entry:08X} */",
            f"/* function: {function.get('name')} */",
            "",
            pseudocode.rstrip(),
            "",
        ]),
        encoding="utf-8",
    )
    return {
        "status": "decompiled",
        "address": f"0x{entry:08X}",
        "name": function.get("name"),
        "path": str(text_path),
        "report": str(report_path),
    }


__all__ = ["decompile_function"]
